export const COMPLETE_TUTORIAL = 'COMPLETE_TUTORIAL';

export const ENTER_DISTRACTED_MODE = 'ENTER_DISTRACTED_MODE';

export const NOTIFY_HALF_TIME = 'NOTIFY_HALF_TIME';

export const NOTIFY_TIME_UP = 'NOTIFY_TIME_UP';

export const RESET_STATE = 'RESET_STATE';

export const START_TIMER = 'START_TIMER';

export const UPDATE_ABOUT_TO_BE_DISTRACTED = 'UPDATE_ABOUT_TO_BE_DISTRACTED';

export const UPDATE_BLOCKED_SITES = 'UPDATE_BLOCKED_SITES';

export const UPDATE_CURRENT_TABS = 'UPDATE_CURRENT_TABS';

export const UPDATE_IS_MOVEABLE = 'UPDATE_IS_MOVEABLE';

export const UPDATE_TASK = 'UPDATE_TASK';

export const UPDATE_TIME_REMAINING = 'UPDATE_TIME_REMAINING';
