export const DECREMENT_TIMER = 'DECREMENT_TIMER';

export const RESET_TASK = 'RESET_TASK';

export const SENT_HALF_TIME_NOTIFICATION = 'SENT_HALF_TIME_NOTIFICATION';

export const SET_ABOUT_TO_BE_DISTRACTED = 'SET_ABOUT_TO_BE_DISTRACTED';

export const SET_ACTIVE = 'SET_ACTIVE';

export const SET_BLOCKED_SITES = 'SET_BLOCKED_SITES';

export const SET_DISTRACTED = 'SET_DISTRACTED';

export const SET_EXPECTED_TIME = 'SET_EXPECTED_TIME';

export const SET_FRESH_STATE = 'SET_FRESH_STATE';

export const SET_IS_MOVEABLE = 'SET_IS_MOVEABLE';

export const SET_OPEN_TABS = 'SET_OPEN_TABS';

export const SET_TASK = 'SET_TASK';

export const SET_TIME_REMAINING = 'SET_TIME_REMAINING';
