export const COMPLETE_DISTRACTION_MODE = 'COMPLETE_DISTRACTION_MODE';

export const COMPLETE_MODE = 'COMPLETE_MODE';

export const DISTRACTION_MODE = 'DISTRACTION_MODE';

export const WIDGET_MODE = 'WIDGET_MODE';
